name: Docker step from GitHub Packages

on:
  workflow_dispatch: 

jobs:
  
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Docker step from GitHub Packages
        uses: docker://ghcr.io/tdupoiron-org/demo-packages:latest