name: Docker Service

on:
  workflow_dispatch: 

jobs:
  app:

    runs-on: ubuntu-latest

    steps:
      - name: wget
        run: |
          wget -O- http://localhost:8080

    services:
      nginx:
        image: nginx
        # Map port 8080 on the Docker host to port 80 on the nginx container
        ports:
          - 8080:80