name: Docker job from GitHub Packages

on:
  workflow_dispatch: 

permissions: 
  packages: read

jobs:

  docker-run:
    runs-on: ubuntu-latest

    container: 
      image: ghcr.io/tdupoiron-org/demo-packages:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Run docker image
        run: |
          echo "hello world"