name: Docker step from GitHub Packages on GHR

on:
  workflow_dispatch: 

permissions: 
  packages: read

jobs:

  docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Docker step from GitHub Packages
        uses: docker://ghcr.io/tdupoiron-org/demo-packages:1698240509
        # Authentication cannot be passed here
        # self-hosted runner can be preauthenticated to private registry with $HOME/.docker/config.json file