name: Call reusable workflow

on:
  workflow_dispatch: 

jobs:
  run:
    uses: tdupoiron-org/demo-private-docker-registry-github-actions/.github/workflows/docker-run-rw.yml@main
    with:
      docker-image-name: tdupoiron-org/demo-packages
      docker-image-tag: 1698240509
      docker-registry-domain: ghcr.io
      docker-registry-username: ${{ github.actor }}
    secrets:
      docker-registry-password: ${{ secrets.GITHUB_TOKEN }}