name: Call reusable workflow

on:
  workflow_dispatch: 

env:
  DOCKER_REGISTRY_DOMAIN: ghcr.io
  DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_IMAGE_NAME: tdupoiron-org/demo-packages
  DOCKER_IMAGE_TAG: 1698240509

jobs:
  run-docker:
    uses: tdupoiron-org/demo-private-docker-registry-github-actions/.github/workflows/docker-run-rw.yml@main
    with:
      docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
      docker-image-tag: ${{ vars.DOCKER_IMAGE_TAG }}
      docker-registry-domain: ${{ vars.DOCKER_REGISTRY_DOMAIN }}
      docker-registry-username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
      docker-registry-password: ${{ vars.DOCKER_REGISTRY_PASSWORD }}