name: Reusable workflow - Run Docker container

on:
  workflow_call: 
    inputs:
      docker-registry-domain:
        type: string
        required: true
      docker-registry-username:
        type: string
        required: true
      docker-image-name:
        type: string
        required: true
      docker-image-tag:
        type: string
        required: true
    
    secrets:
      docker-registry-password:
        required: true

permissions: 
  packages: read

jobs:

  docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.docker-registry-domain }}
          username: ${{ inputs.docker-registry-username }}
          password: ${{ secrets.docker-registry-password }}

      - name: Pull image
        run: docker pull ${{ inputs.docker-registry-domain }}/${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }}

      - name: Run image
        run: docker run ${{ inputs.docker-registry-domain }}/${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }}